# Generated by Django 3.1.6 on 2021-02-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210217_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('drama', 'DRAMA'), ('comdey', 'COMEDY'), ('romance', 'ROMANCE')], max_length=10),
        ),
    ]
