# Generated by Django 3.1.6 on 2021-02-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20210217_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='langugage',
            new_name='language',
        ),
    ]
